# -*- coding: utf-8 -*-

# Inforevealer
# Copyright (C) 2010  Francois Boulogne <fboulogne at april dot org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.




def print_write_header(fhandler):
        header=''' 
                                                ~~~~~~~~~~~~~~~
                                                Log generated by 
                                                  Inforevealer
                                                ~~~~~~~~~~~~~~~
                                   Distributed under the GNU GPLv2 licence
                                Francois Boulogne <fboulogne at april dot org>
                                    http://github.com/sciunto/inforevealer
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'''
	print(header)
	fhandler.write(header)
                


def write_title(string,output):
	title=""
	if string.__class__ != str:
		for i in string:
			title+= i+" "
        else:
		title=string

	header= '#############################################'
	header= header + '\n' + '#   ' + title + '\n'
	header=header+'#############################################\n'
	output.write(header)
